# Declare stages
stages:
  - init
  - build
  - test
  - coverage
  - test_install
  - deploy

# Default variables and parameters
variables:
  CUSTOM_CI_BUILDS_DIR: $WORKDIR/test # inactif car option non activee dans la configuration du runner
  GIT_STRATEGY: none # don't do anything by default
  BUILD_MAX_DURATION: "00:30:00"
  TESTS_MAX_DURATION: "01:00:00"
  SCHEDULER_PARAMETERS: "--partition=intel --cpus-per-task=1 --ntasks=1 --nodes=1-1 --time=00:30:00"
  # CI_DEBUG_TRACE: "true" #Uncomment to debug CI
default:
  id_tokens:
    CI_JOB_JWT:
      aud: https://gitlab.onera.net
  tags: # All jobs uses jacamar-slurm executor
    - juno-slurm

job:init_repo:
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: none
  stage: init
  script: # explicitly load modules one by one, so that if one fails, it will be easy to identify
    - echo "Clone directory $PWD"
    - echo "CUSTOM_CI_DIR=$PWD" >> build.env
    - git submodule update --init external/paradigm
  artifacts:
    reports:
      dotenv: build.env

job:build:
  parallel:
    matrix:
      - COMPILER: "gcc@15"
        MPI_LIB:
          - "openmpi"
        BUILD_TYPE:
          - "Sanitize"
      - COMPILER: "gcc@14"
        MPI_LIB:
          - "openmpi"
        BUILD_TYPE:
          - "Sanitize"
      - COMPILER: "gcc@12"
        MPI_LIB:
          - "intel-oneapi"
        BUILD_TYPE:
          - "Sanitize"
      - COMPILER: "gcc@10"
        MPI_LIB:
          - "openmpi"
        BUILD_TYPE:
          - "Debug"
      - COMPILER: "gcc@10"
        MPI_LIB:
          - "intel-oneapi"
        BUILD_TYPE:
          - "Sanitize"
      - COMPILER: "intel-llvm@2022"
        MPI_LIB:
          - "intel-oneapi"
        BUILD_TYPE:
          - "Debug"
  variables:
    MATRIX_KEY: _${COMPILER}_${MPI_LIB}_BUILD_${BUILD_TYPE}
    SCHEDULER_PARAMETERS: "--partition=intel --cpus-per-task=1 --ntasks=12 --nodes=1-1 --time=${BUILD_MAX_DURATION}"
  stage: build
  before_script:
    - module purge
    - if   [ "${COMPILER}" == "gcc@15" ]; then
    -   source /tmp_user/juno/sonics/dist/socle_cfd7/source_gcc15_cython3.sh || true
    - elif [ "${COMPILER}" == "gcc@14" ]; then
    -   source /tmp_user/juno/sonics/dist/socle_cfd7/source_gcc14_cython3.sh || true
    - else
    -   source /tmp_user/juno/sonics/dist/source_juno_all.sh --compiler=$COMPILER --mpi=$MPI_LIB || true
    - fi
  script:
    - cd $CUSTOM_CI_DIR
    - mkdir -p build$MATRIX_KEY && cd build$MATRIX_KEY
    - if   [ "${COMPILER}" == "gcc@15" ]; then
    -   cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCWP_ENABLE_EXTERNAL_PDM=OFF -DCWP_ENABLE_PYTHON_BINDINGS=ON  -DCWP_ENABLE_STATIC=OFF -DCWP_ENABLE_HIDE_PDM_SYMBOLS=OFF -DCWP_ENABLE_SHARED=ON -DCWP_ENABLE_Fortran=ON  -DCWP_ENABLE_Fortran_MPI_MODULE=OFF -DCWP_ENABLE_DOCUMENTATION=OFF -DCWP_ENABLE_BLASLAPACK=OFF -DCWP_ENABLE_CLIENT_SERVER=ON  -DCWP_ENABLE_UNIT_TESTS=ON ../
    - elif [ "${COMPILER}" == "gcc@14" ]; then
    -   cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCWP_ENABLE_EXTERNAL_PDM=OFF -DCWP_ENABLE_PYTHON_BINDINGS=ON  -DCWP_ENABLE_STATIC=OFF -DCWP_ENABLE_HIDE_PDM_SYMBOLS=ON  -DCWP_ENABLE_SHARED=ON -DCWP_ENABLE_Fortran=ON  -DCWP_ENABLE_Fortran_MPI_MODULE=OFF -DCWP_ENABLE_DOCUMENTATION=OFF -DCWP_ENABLE_BLASLAPACK=OFF -DCWP_ENABLE_CLIENT_SERVER=ON  -DCWP_ENABLE_UNIT_TESTS=ON ../
    - elif [ "${COMPILER}" == "gcc@12" ]; then
    -   cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCWP_ENABLE_EXTERNAL_PDM=OFF -DCWP_ENABLE_PYTHON_BINDINGS=ON  -DCWP_ENABLE_STATIC=ON  -DCWP_ENABLE_HIDE_PDM_SYMBOLS=OFF -DCWP_ENABLE_SHARED=ON -DCWP_ENABLE_Fortran=ON  -DCWP_ENABLE_Fortran_MPI_MODULE=OFF -DCWP_ENABLE_DOCUMENTATION=OFF -DCWP_ENABLE_BLASLAPACK=OFF -DCWP_ENABLE_CLIENT_SERVER=ON  -DCWP_ENABLE_UNIT_TESTS=ON ../
    - elif [ "${COMPILER}" == "gcc@10" ]; then
    -   cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCWP_ENABLE_EXTERNAL_PDM=OFF -DCWP_ENABLE_PYTHON_BINDINGS=ON  -DCWP_ENABLE_STATIC=OFF -DCWP_ENABLE_HIDE_PDM_SYMBOLS=ON  -DCWP_ENABLE_SHARED=ON -DCWP_ENABLE_Fortran=ON  -DCWP_ENABLE_Fortran_MPI_MODULE=ON  -DCWP_ENABLE_DOCUMENTATION=OFF -DCWP_ENABLE_BLASLAPACK=OFF -DCWP_ENABLE_CLIENT_SERVER=ON  -DCWP_ENABLE_UNIT_TESTS=ON ../
    - elif [ "${COMPILER}" == "intel-llvm@2022" ]; then
    -   cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCWP_ENABLE_EXTERNAL_PDM=OFF -DCWP_ENABLE_PYTHON_BINDINGS=OFF -DCWP_ENABLE_STATIC=OFF -DCWP_ENABLE_HIDE_PDM_SYMBOLS=ON  -DCWP_ENABLE_SHARED=ON -DCWP_ENABLE_Fortran=OFF -DCWP_ENABLE_Fortran_MPI_MODULE=OFF -DCWP_ENABLE_DOCUMENTATION=OFF -DCWP_ENABLE_BLASLAPACK=OFF -DCWP_ENABLE_CLIENT_SERVER=OFF -DCWP_ENABLE_UNIT_TESTS=ON ../
    - fi
    - make -j

job:build_doc:
  tags:
    - juno-shell
  stage: build
  before_script:
    - module purge
    - source /tmp_user/juno/sonics/dist/source_juno_all.sh --compiler=intel@2022 --mpi=intel-oneapi || true
    - module load texlive
  script:
    - cd $CUSTOM_CI_DIR
    - mkdir -p build_intel@2022_intel-oneapi_BUILD_Debug && cd build_intel@2022_intel-oneapi_BUILD_Debug
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCWP_ENABLE_EXTERNAL_PDM=OFF -DCWP_ENABLE_PYTHON_BINDINGS=ON -DCWP_ENABLE_STATIC=OFF -DCWP_ENABLE_HIDE_PDM_SYMBOLS=ON -DCWP_ENABLE_SHARED=ON -DCWP_ENABLE_Fortran=ON -DCWP_ENABLE_Fortran_MPI_MODULE=ON -DCWP_ENABLE_DOCUMENTATION=ON -DCWP_ENABLE_BLASLAPACK=OFF -DCWP_ENABLE_CLIENT_SERVER=ON -DCWP_ENABLE_UNIT_TESTS=ON ../
    - make -j

job:build_coverage:
  variables:
    SCHEDULER_PARAMETERS: "--partition=intel --cpus-per-task=1 --ntasks=12 --nodes=1-1 --time=${BUILD_MAX_DURATION}"
  stage: build
  before_script:
    - module purge
    - source /tmp_user/juno/sonics/dist/source_juno_all.sh --compiler=gcc@12 --mpi=intel-oneapi || true
  script:
    - cd $CUSTOM_CI_DIR
    - mkdir -p build_coverage && cd build_coverage
    - cmake -DCMAKE_BUILD_TYPE="Coverage" -DCWP_ENABLE_EXTERNAL_PDM=OFF -DCWP_ENABLE_PYTHON_BINDINGS=ON -DCWP_ENABLE_STATIC=OFF -DCWP_ENABLE_SHARED=ON -DCWP_ENABLE_Fortran=ON -DCWP_ENABLE_Fortran_MPI_MODULE=OFF -DCWP_ENABLE_DOCUMENTATION=OFF -DCWP_ENABLE_BLASLAPACK=OFF -DCWP_ENABLE_CLIENT_SERVER=ON -DCWP_ENABLE_UNIT_TESTS=ON ../
    - make -j

unit_test:cwipi:
  parallel:
    matrix:
      - COMPILER: "gcc@15"
        MPI_LIB:
          - "openmpi"
        BUILD_TYPE:
          - "Sanitize"
      - COMPILER: "gcc@14"
        MPI_LIB:
          - "openmpi"
        BUILD_TYPE:
          - "Sanitize"
      - COMPILER: "gcc@12"
        MPI_LIB:
          - "intel-oneapi"
        BUILD_TYPE:
          - "Sanitize"
      - COMPILER: "gcc@10"
        MPI_LIB:
          - "openmpi"
        BUILD_TYPE:
          - "Debug"
      - COMPILER: "gcc@10"
        MPI_LIB:
          - "intel-oneapi"
        BUILD_TYPE:
          - "Sanitize"
      - COMPILER: "intel-llvm@2022"
        MPI_LIB:
          - "intel-oneapi"
        BUILD_TYPE:
          - "Debug"
      - COMPILER: "intel@2022"
        MPI_LIB:
          - "intel-oneapi"
        BUILD_TYPE:
          - "Debug"
  variables:
    MATRIX_KEY: _${COMPILER}_${MPI_LIB}_BUILD_${BUILD_TYPE}
    SCHEDULER_PARAMETERS: "--partition=intel --cpus-per-task=1 --ntasks=12 --nodes=1-1 --time=${TESTS_MAX_DURATION}"
  stage: test
  before_script:
    - module purge
    - if   [ "${COMPILER}" == "gcc@15" ]; then
    -   source /tmp_user/juno/sonics/dist/socle_cfd7/source_gcc15_cython3.sh || true
    - elif [ "${COMPILER}" == "gcc@14" ]; then
    -   source /tmp_user/juno/sonics/dist/socle_cfd7/source_gcc14_cython3.sh || true
    - else
    -   source /tmp_user/juno/sonics/dist/source_juno_all.sh --compiler=$COMPILER --mpi=$MPI_LIB || true
    - fi
  script:
    - cd $CUSTOM_CI_DIR/build$MATRIX_KEY
    - export NAvailRank=12
    - ./cwp_run -ics -timeout 5

unit_test:clt-intel-oneapi:
  needs: [job:init_repo, job:build, unit_test:cwipi]
  tags:
    - juno-shell
  stage: test
  before_script:
    - module purge
    - source /tmp_user/juno/sonics/dist/source_juno_all.sh --compiler=gcc@12 --mpi=intel-oneapi || true
  script:
    - cd $CUSTOM_CI_DIR/build_gcc@12_intel-oneapi_BUILD_Sanitize
    - ./cwp_run -incs -scs -timeout 5

job:coverage_report:
  tags:
    - juno-shell
  stage: coverage
  before_script:
    - module purge
    - source /tmp_user/juno/sonics/dist/source_juno_all.sh --compiler=gcc@12 --mpi=intel-oneapi || true
  script:
    - cd $CUSTOM_CI_DIR/build_coverage
    - ./cwp_run -scs -timeout 5
    - cd $CUSTOM_CI_DIR/build_coverage/src/CMakeFiles/cwp.dir/new
    - gcov -b -l -p -c *.gcno
    - cd $CUSTOM_CI_DIR/build_coverage
    - gcovr --gcov-ignore-parse-errors -g -k --xml-pretty --print-summary --root ${CUSTOM_CI_DIR}/src --object-directory ${CUSTOM_CI_DIR}/build_coverage --output $CI_PROJECT_DIR/coverage.xml
  when: on_success
  coverage: /lines:\s*(\d+\.\d+)%/
  artifacts:
    when: always
    reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml

fake_install:
  variables:
    SCHEDULER_PARAMETERS: "--partition=intel --cpus-per-task=1 --ntasks=12 --nodes=1-1 --time=${BUILD_MAX_DURATION}"
  stage: test_install
  before_script:
    - module purge
    - source /tmp_user/juno/sonics/dist/source_juno_all.sh --compiler=gcc@12 --mpi=intel-oneapi || true
  script:
    - cd $CUSTOM_CI_DIR
    - mkdir -p build_fake_install && cd build_fake_install
    - export CWIPI_INSTALL_ROOT=${PWD}/fake_install
    - cmake -DCMAKE_INSTALL_PREFIX=${CWIPI_INSTALL_ROOT} -DCMAKE_BUILD_TYPE=Release -DCWP_ENABLE_EXTERNAL_PDM=OFF -DCWP_ENABLE_HIDE_PDM_SYMBOLS=OFF -DCWP_ENABLE_PYTHON_BINDINGS=ON -DCWP_ENABLE_STATIC=ON -DCWP_ENABLE_SHARED=ON -DCWP_ENABLE_Fortran=ON -DCWP_ENABLE_Fortran_MPI_MODULE=OFF -DCWP_ENABLE_DOCUMENTATION=OFF -DCWP_ENABLE_BLASLAPACK=OFF -DCWP_ENABLE_CLIENT_SERVER=ON ../
    - make -j install
    - cd $CUSTOM_CI_DIR
    - mkdir -p test_fake_install && cd test_fake_install
    - export CWIPI_ROOT=${CWIPI_INSTALL_ROOT}
    - cmake ../cmake/check_install/

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  pages: True
  script:
    - rm -rf public
    - mkdir public
    - cp -r /tmp_user/juno/cwipi/usr/doc/html/* public/
    - cp -r $CUSTOM_CI_DIR/build_intel@2022_intel-oneapi_BUILD_Debug/doc/sphinx/html public/dev
    - |
      cat > public/index.html << EOF
      <head>
        <meta http-equiv='refresh' content='0; URL=dev/index.html'>
      </head>
      EOF
  artifacts:
    paths:
      - public