write(*,'(/a )')'------------------------------------------------------------------------'
write(*,'( a )')'                      program Bases Nodales                             '
write(*,'( a )')'         Copyright (c) ONERA, 1995-2013. All rights reserved            '
write(*,'( a )')' Developped by Christophe Peyret tel: 0146734778 mail: peyret@onera.fr  '
write(*,'( a )')'                                                                        '
write(*,'( a )')' Compiled on Mer 3 jul 2013 13:29:11 CEST with santafe.onera  '
write(*,'( a )')'                                     '
write(*,'( a )')'                                           '
write(*,'( a/)')'------------------------------------------------------------------------'
