
# include:
#   # Metadata shared my many jobs
#   - local: .gitlab/common_build.yaml


.spiro_el8:before_script:default:
  before_script:
    - echo $PWD
  variables:
    BUILD_DIR: build_${COMPILER}_${MPI_LIB}
    ARCTIFACTS_CTEST_NAME: ./build$COMPILER/paradigm_ctest_$COMPILER.xml

.spiro_el8:init:default:
  stage: init
  tags:
    - slurm
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: none
    SCHEDULER_PARAMETERS:  "-M rhel8 --qos=el8_gbe --cpus-per-task=24 --ntasks=1 --time=00:30:00"
  before_script:
    - hostname
    - whoami
    - unset _LMFILES_
    - unset LOADEDMODULES
    - module -s purge
  script:
    - echo "CUSTOM_CI_DIR=$PWD" >> build.env
    - git submodule update --init extensions/paradigma
    - echo $CUSTOM_CI_DIR
  artifacts:
    reports:
      dotenv: build.env


.spiro_el8:build:default:
  stage: build
  tags:
    - slurm
  before_script:
    - hostname
    - whoami
    - unset _LMFILES_
    - unset LOADEDMODULES
    - module -s purge
    - source /scratchm/sonics/dist/spiro-el8.sh --compiler=${COMPILER} --mpi=${MPI_LIB}
    - echo $MPICC
  script:
    - cd $CUSTOM_CI_DIR
    - echo ${BUILD_DIR}
    - echo ${ARCTIFACTS_CTEST_NAME}
    - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
    - echo $PWD
    - which mpirun
    - echo $MPICC
    - echo $CC
    - mpicc -show
    - cmake -DCMAKE_BUILD_TYPE=Sanitize -DPDM_ENABLE_STATIC=OFF -DPDM_ENABLE_SHARED=ON -DPDM_ENABLE_Fortran=OFF -DPDM_ENABLE_EXTENSION_PDMA=ON ../
    - make -j 24

.spiro_el8:test:default:
  stage: test
  tags:
    - slurm
  before_script:
    - hostname
    - whoami
    - unset _LMFILES_
    - unset LOADEDMODULES
    - unset LOADEDMODULES
    - module -s purge
    - source /scratchm/sonics/dist/spiro-el8.sh --compiler=${COMPILER} --mpi=${MPI_LIB}
  script:
    - cd $CUSTOM_CI_DIR
    - cd ${BUILD_DIR}
    - echo $PWD
    - echo $LSAN_OPTIONS
    - export LSAN_OPTIONS=suppressions=/stck/bmaugars/dev/dev-Tools/paradigma/build/spiro_gcc_py3/suppression_asan.txt
    - ctest --output-junit paradigm_ctest_${COMPILER}_${MPI_LIB}.xml -V -R pdm_t_cellface
    - cp paradigm_ctest_${COMPILER}_${MPI_LIB}.xml $CI_PROJECT_DIR
  artifacts:
    when: always
    reports:
      junit:
        - "paradigm_ctest_${COMPILER}_${MPI_LIB}.xml"

stages:
  - init
  - build
  - test
  # - post
  # - deploy

job_spiro_el8:init:
  extends:
    - .spiro_el8:init:default

include:
  - local: '.gitlab/matrix/spiro-el8-gcc-impi.yaml'
