#!/bin/sh

PWD1=`pwd`

if [ ! -d sbin ]; then
  echo "$0 must be called from top directory (../$0)"
  exit 1
fi

# ____________________________________________________________________
# aclocal creates the aclocal.m4 file from the standard macro and the
# custom macro embedded in the directory /config
# and KERNEL config_files directory.
# output:
#   aclocal.m4
#   autom4te.cache (directory)
echo "====================================================== aclocal"

  aclocal -I config || exit 1

# ____________________________________________________________________
# libtoolize creates some configuration files (ltmain.sh,
# config.guess and config.sub). It only depends on the libtool
# version. The files are created in the directory specified with the
# AC_CONFIG_AUX_DIR(<mydir>) tag (see configure.ac).
# output:
#   config/config.guess
#   config/config.sub
#   config/ltmain.sh
#
echo "====================================================== libtoolize"

libtoolize --force --copy --automake || exit 1

# ____________________________________________________________________
# autoconf creates the configure script from the file configure.ac (or
# configure.in if configure.ac doesn't exist)
# output:
#   configure
echo "====================================================== autoconf"

autoconf

# ____________________________________________________________________
# automake creates some scripts used in building process
# (install-sh, missing, ...). It only depends on the automake
# version. The files are created in the directory specified with the
# AC_CONFIG_AUX_DIR(<mydir>) tag (see configure.ac). This step also
# creates the Makefile.in files from the Makefile.am files.
# output:
#   config/compile
#   config/depcomp
#   config/install-sh
#   config/missing
#   config/py-compile
#   Makefile.in (from Makefile.am)
echo "====================================================== automake"

automake --copy --add-missing

\rm -rf autom4te.cache

# ____________________________________________________________________
# cython create the Python API of CWIPI 
# output:
#   cython/CWIPI.c
echo "====================================================== cython"

cd cython
PYTHON=python
CYTHON=cython
PYTHON_INCLUDE=`${PYTHON} -c 'from distutils import sysconfig; print( sysconfig.get_python_inc() )'`
MPI4PY_INCLUDE=`${PYTHON} -c 'import mpi4py; print( mpi4py.get_include() )'`
NUMPY_INCLUDE=`${PYTHON} -c 'import numpy; print( numpy.get_include() )'`
CWIPI_INCLUDE=${PWD1}/src

${CYTHON} -a  -I${MPI4PY_INCLUDE} -I{CWIPI_INCLUDE} -I{NUMPY_INCLUDE} CWIPI.pyx

cd ${PWD1}