C
C COUPLINGS_NATURE_T
      INTEGER COUPLINGS_NATURE_ELEMENT_CENTER 
      INTEGER COUPLINGS_NATURE_NODE
      PARAMETER (COUPLINGS_NATURE_ELEMENT_CENTER = 0)
      PARAMETER (COUPLINGS_NATURE_NODE = 1)
C
C COUPLINGS_DIMENSION_T
      INTEGER COUPLINGS_DIMENSION_SCALAR
      INTEGER COUPLINGS_DIMENSION_INTERLACED_VECTOR
      PARAMETER (COUPLINGS_DIMENSION_SCALAR = 0)
      PARAMETER (COUPLINGS_DIMENSION_INTERLACED_VECTOR = 1)
C
C COUPLINGS_TYPE_T
      INTEGER COUPLINGS_TYPE_FLOAT
      INTEGER COUPLINGS_TYPE_DOUBLE
      PARAMETER (COUPLINGS_TYPE_FLOAT = 0)
      PARAMETER (COUPLINGS_TYPE_DOUBLE = 1)
C
C COUPLINGS_INTERPOLATION_T
      INTEGER COUPLINGS_INTERPOLATION_STANDARD
      INTEGER COUPLINGS_INTERPOLATION_USER 
      PARAMETER(COUPLINGS_INTERPOLATION_STANDARD = 0)
      PARAMETER(COUPLINGS_INTERPOLATION_USER = 1)
C
C COUPLINGS_NOT_LOCATED_POINT_TREATMENT_T
      INTEGER COUPLINGS_NOT_LOCATED_POINT_TREATMENT_STANDARD 
      INTEGER COUPLINGS_NOT_LOCATED_POINT_TREATNENT_USER
      PARAMETER(COUPLINGS_NOT_LOCATED_POINT_TREATMENT_STANDARD = 0)
      PARAMETER(COUPLINGS_NOT_LOCATED_POINT_TREATNENT_USER = 1)
C
C IFILE
      INTEGER IFILE
      COMMON /CCOUPLING/ IFILE
